[package]
name = "libraw_r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.1" , optional = true }
img-parts = { version = "0.2.3", optional = true }
libraw-sys = { git = "https://github.com/aftershootco/libraw-sys", branch = "update-libraw" }
thiserror = "1.0.30"

[target.'cfg(windows)'.dependencies]
widestring = "0.5.1"

[features]
jpeg = ["dep:image", "dep:img-parts"]
default = []
